### ISSUE TITLE
ESP32 Compatibility

### ISSUE THREAD

**Issue by JWBuilds** [SolderedElectronics/Soldered-Simple-Sensor-Arduino-Library#1]
Hi there,

I'm trying to connect the following sensors to an ESP32 (Wroom 32):
- [Simple rain sensor](https://soldered.com/product/simple-rain-sensor/)
- [Simple soil humidity senso](https://soldered.com/product/simple-soil-humidity-sensor/)

For the purposes of this issue, I'll focus on the simple rain sensor, I'm assuming the fix is very similar for the soil humidity sensor. 

My current ESP32/Rain sensor wiring is the following: 

VIN -> VCC
GND -> GND
D22 (SCL) -> A0
D21 (SDA) -> D0

The ESP32 board pinout is the following: 
![esp32](https://github.com/SolderedElectronics/Soldered-Simple-Sensor-Arduino-Library/assets/13793247/6f72c6e2-298e-4034-bbd9-a3d85e88f1c4)

I've setup a platformio project, installed the Simple-Sensor-SOLDERED, Simple-Rain_Sensor-Soldered libraries and they build correctly. 

My code currently looks like this: 

```
#include <Wire.h>
#include <PMserial.h>

// for onboard LED
#define LED 2

#include "Simple-Rain-Sensor-SOLDERED.h"
// Create the sensor object
simpleRainSensor rainSensor;

void setup()
{
  Serial.begin(115200); // Begin Serial communication so we can see the output
  rainSensor.begin();   // Init the Simple Rain Sensor

  // If you're starting the sensor on a different address, use this constructor
  rainSensor.begin(0x30);

  // The default address is 0x30
  // You may change the address via the switches on the front of the board
  // In this table, 'x' represents a switch toggled 'UP'
  // Note that on the physical switches 1 and 3 are swapped
  // Address | 3 | 2 | 1 |
  // 0x30    |   |   |   |
  // 0x31    |   |   | x |
  // 0x32    |   | x |   |
  // 0x33    |   | x | x |
  // 0x34    | x |   |   |
  // 0x35    | x |   | x |
  // 0x36    | x | x |   |
  // 0x37    | x | x | x |

  rainSensor.setThreshold(35.5); // Set the threshold for reading is it raining or not
  // Sensor calibration isn't needed but it helps with getting more relevant readings.
  // To calibrate the sensor, first run this sketch with the line of code below commented:
  // rainSensor.calibrate(76.4);

  // Place the sensor in water - so it's as wet as you're ever going to want to measure.
  // Note the reading of the Rain percentage, and then write that value in the calibrate function.
  // What this does is essentially make the range of measurement smaller so the data you get is more relevant.

  // Optionally, Invert the LED on the board
  // rainSensor.invertLED(true);
  pinMode(LED, OUTPUT);
}

void loop()
{
  Serial.println();
  Serial.println();

  Serial.println();
  Serial.println();

  digitalWrite(LED, HIGH);
  Serial.println("LED is on");
  Serial.println();

  // Print the readings to Serial

  // Raw reading is essentially a reading of the analog value on the easyC board
  Serial.print("Raw reading: ");
  Serial.println(rainSensor.getRawReading());

  // The resistance is calcualted through a constant
  Serial.print("Resistance: ");
  Serial.print(rainSensor.getResistance());
  Serial.println(" Ohm.");

  // Print percentage of rain detected on sensor
  Serial.print("Rain percentage: ");
  Serial.print(rainSensor.getValue());
  Serial.println("%");

  // Print is it raining or not
  // Once again, you may adjust this threshold with setThreshold
  Serial.print("Is it raining? ");
  if (rainSensor.isRaining())
    Serial.println("True!");
  else
    Serial.println("False!");

  Serial.println(); // Print newline

  digitalWrite(LED, LOW);
  Serial.println("LED is off");
  delay(1000); // Wait a bit until the next reading
}
```

I've followed the guides from the official repo but I'm encountering the following error: ```[323613][E][Wire.cpp:513] requestFrom(): i2cRead returned Error 263```

I'm assuming it's linked to the fact that I need to declare the pins used somewhere or that the wiring is incorrect when using an ESP32. Any guidance would be much appreciated ! 

Thanks in advance for the help !

**Comment by AN63L** [comment]
So it ended up being a beginner's wiring issue...

Simply update your wiring 

D0 -> D4
A0 -> D34

And when initialising the sensor: 

```
// Create the sensor object
#define SENSOR_A0_PIN 34
#define SENSOR_D0_PIN 4
simpleRainSensor rainSensor(SENSOR_A0_PIN, SENSOR_D0_PIN);
```

**Comment by JWBuilds** [comment]
So it ended up being a beginner's wiring issue...

Simply update your wiring

D0 -> D4
A0 -> D34

And when initialising the sensor:

// Create the sensor object
#define SENSOR_A0_PIN 34
#define SENSOR_D0_PIN 4
simpleRainSensor rainSensor(SENSOR_A0_PIN, SENSOR_D0_PIN);

**Comment by rsoric** [comment]
Hi @AN63L , D0 is a digital pin and A0 an analog one, you can use basically any pin on ESP32.

I appreciate you sharing your answer here.
